# Generated by Django 5.0.4 on 2024-04-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userprofile_age_userprofile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatus',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
