# Generated by Django 5.0.4 on 2024-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profilestatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatus',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
